### ISSUE TITLE
get products by stock amount endpoints

### ISSUE THREAD

**Issue by GaKa00** [JohanTran02/IMS#42]
```
  //TODO get products by stock amount endpoints @GaKa00 
```

https://github.com/JohanTran02/IMS/blob/5e1d7eb04b6b0a2fa6c73c21d922b8e4b2f4a3ce/backend/resources/product/products.controller.ts#L203

**Comment by JohanTran02** [comment]
[Answer to issue](https://github.com/JohanTran02/IMS/pull/43#discussion_r1754191331)

**Comment by JohanTran02** [comment]
closed #48
